  - name: Template and copy the git-lfs-s3-server site file
    template:
      src: "git-lfs-s3-server.conf.j2"
      dest: "/etc/nginx/sites-enabled/git-lfs-s3-server.conf"
    become: true
    become_user: root

  - name: Template and copy the secrets file for passenger
    template:
      src: "secrets-passenger.conf.j2"
      dest: "/etc/nginx/conf.d/secrets-passenger.conf"
    become: true
    become_user: root

  - name: Copy the SSL cert
    copy:
      src: "roles/git-lfs-s3-server/files/server.crt"
      dest: "/etc/ssl/certs/server.crt"
    become: true
    become_user: root

  - name: Copy the SSL key
    copy:
      src: "roles/git-lfs-s3-server/files/server.key"
      dest: "/etc/ssl/private/server.key"
    become: true
    become_user: root

  - name: Create the LFS server app directory
    file:
      path: "{{ lfs_app_location }}"
      state: directory
      owner: ubuntu
      group: www-data
      mode: 0777
      recurse: yes
    become: true

  - name: Deploy the LFS server app
    copy:
      src: "{{ item }}"
      dest: "{{ lfs_app_root }}"
      owner: ubuntu
      group: www-data
    with_items:
      - Gemfile
      - config.ru
      - git-lfs-s3-server.rb
    become: true

  - name: Use Bundler to install the gem dependencies
    command: "bash -lc '. ~/.rvm/scripts/rvm; rvm use {{ ruby_version }} --silent && bundle install'"
    become: true
    become_user: ubuntu
    args:
      chdir: "{{ lfs_app_root }}"

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
    become: true