--- 
- 
  hosts: lfs
  name: Configure servers with RVM
  roles: 
    - 
      role: rvm1
      rvm1_rubies: 
        - ruby-2.4.0
      rvm1_user: ubuntu
      tags: ruby
    -
      role: passenger
      passenger_ruby: /home/ubuntu/.rvm/gems/ruby-2.4.0/wrappers/ruby